Repository 2023-Winter-Bootcamp-Team-K/Backend, pull requests merged in 2024-01, with the labels that each got.

#5 Chore : Django 기초 세팅
  .gitignore
  .idea/.gitignore
  .idea/Backend.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  backend/Dockerfile
  backend/apps/__init__.py
  backend/apps/admin.py
  backend/apps/apps.py
  backend/apps/models.py
  backend/apps/tests.py
  backend/apps/views.py
  backend/backend/Pipfile
  backend/backend/__init__.py
  backend/backend/asgi.py
  backend/backend/settings.py
  backend/backend/urls.py
  backend/backend/wsgi.py
  backend/manage.py
  backend/requirements.txt
  docker-compose.yml
  nginx/Dockerfile
  nginx/nginx.conf
Labels: Chore

#9 Chore: db 컨테이너 추가
  backend/Pipfile
  backend/backend/Pipfile
  backend/backend/settings.py
  backend/backend/urls.py
  docker-compose.yml
Labels: Chore

#11 chore: Dockerfile, docker-compose 수정
  backend/Dockerfile
  docker-compose.yml
Labels: Chore

#15 Chore : mysql에 table 생성 오류 해결
  backend/Dockerfile
  backend/Pipfile
  backend/apps/apps.py
  backend/apps/consumers.py
  backend/apps/models.py
  backend/apps/routing.py
  backend/backend/asgi.py
  backend/backend/urls.py
  backend/config/__init__.py
  backend/config/asgi.py
  backend/config/settings.py
  backend/config/urls.py
  backend/config/wsgi.py
  backend/manage.py
  backend/requirements.txt
Labels: Chore

#16 Chore : docker compose 마이그레이션 코드 추가
  .gitignore
  .idea/Backend.iml
  .idea/misc.xml
  docker-compose.yml
Labels: Chore

#17 Chore : dockerise를 이용해서 db가 켜진다음 장고 실행
  .gitignore
  backend/Dockerfile
  docker-compose.yml
Labels: Chore

#18 Chore: db 테이블 생성 가능
  .gitignore
  backend/apps/models.py
  backend/config/settings.py
  docker-compose.yml
Labels: Chore

#20 Feat/#19
  .idea/Backend.iml
  .idea/misc.xml
  backend/apps/views.py
  backend/config/settings.py
  backend/config/urls.py
  backend/main/__init__.py
  backend/main/admin.py
  backend/main/apps.py
  backend/main/models.py
  backend/main/tests.py
  backend/main/urls.py
  backend/main/views.py
  backend/requirements.txt
  backend/users/__init__.py
  backend/users/admin.py
  backend/users/apps.py
  backend/users/models.py
  backend/users/serializers.py
  backend/users/tests.py
  backend/users/urls.py
  backend/users/views.py
Labels: Feat

#21 Feat : websocket 연결
  backend/apps/consumers.py
  backend/apps/models.py
  backend/apps/routing.py
  backend/apps/templates/chat/index.html
  backend/apps/templates/chat/room.html
  backend/apps/urls.py
  backend/apps/views.py
  backend/config/asgi.py
  backend/config/settings.py
  backend/config/urls.py
  backend/main/models.py
  backend/requirements.txt
Labels: Feat

#28 Feat/#22 : 채팅방 생성 기능 구현
  backend/apps/models.py
  backend/apps/serializers.py
  backend/apps/urls.py
  backend/apps/views.py
  backend/config/settings.py
Labels: Feat

#42 Feat : STT와 첫 대화 내용 저장 기능 구현
  .idea/Backend.iml
  .idea/misc.xml
  Pipfile
  backend/Dockerfile
  backend/apps/chat_consumer.py
  backend/apps/consumers.py
  backend/apps/models.py
  backend/apps/routing.py
  backend/apps/templates/chat/index.html
  backend/apps/templates/chat/room.html
  backend/apps/views.py
  backend/config/asgi.py
  backend/config/settings.py
  backend/requirements.txt
  backend/storage.py
  backend/stt.py
Labels: Feat

#44 feat : GPT 대화 기능 구현
  backend/apps/chat_consumer.py
Labels: Feat

#48 Feat : s3 음성파일 저장완료!
  .idea/Backend.iml
  .idea/misc.xml
  backend/apps/chat_consumer.py
  backend/apps/views.py
  backend/config/settings.py
  backend/storage.py
Labels: Feat

#49 Feat : 대화 내용 저장, 종료, 음성파일 S3 저장
  .idea/misc.xml
  backend/apps/chat_consumer.py
  backend/storage.py
Labels: Feat

#53 Feat: TTS 음성 전송 완료
  backend/apps/chat_consumer.py
  backend/stt.py
  backend/tts.py
Labels: Feat

#57 Feat/#52 s3이미지파일 업로드 코드 & token bearer추가
  .idea/misc.xml
  backend/diary/views.py
  backend/main/urls.py
  backend/main/views.py
  backend/users/views.py
Labels: Feat

#62 Chore : 인데 급하게 chat room 생성 수정함. & celery관련 코드도 몇개 올림.
  backend/apps/serializers.py
  backend/apps/views.py
  backend/config/celery.py
  backend/config/settings.py
  backend/requirements.txt
Labels: Chore, Fix

#63 Fix : useranswer content 값 수정 & docker compose migrate 1번만 실행 되도록 함
  backend/apps/chat_consumer.py
  backend/stt.py
  docker-compose.yml
Labels: Fix

#67 Feat: 메세지 출처 표기 구현, 아이 메세지 text 전송 구현
  .idea/misc.xml
  backend/apps/chat_consumer.py
Labels: Feat

#69 Feat: 아이디 중복확인 추가
  backend/users/urls.py
  backend/users/views.py
Labels: Feat

#73 Fix: 회원가입 중복 오류 수정
  backend/users/serializers.py
Labels: Fix

#74 Chore : celery & rabbitMQ연동 (s3음성파일 저장, stt처리, Dall-e) 비동기처리 완료
  .idea/Backend.iml
  .idea/misc.xml
  backend/apps/chat_consumer.py
  backend/apps/tasks.py
  backend/apps/views.py
  backend/config/celery.py
  backend/config/settings.py
  backend/main/views.py
  backend/storage.py
  backend/stt.py
  backend/users/urls.py
  backend/users/views.py
  docker-compose.yml
Labels: Chore, Feat

#76 Chore: nginx 구현 완료
  .idea/Backend.iml
  .idea/misc.xml
  backend/Dockerfile
  backend/apps/chat_consumer.py
  backend/apps/tasks.py
  backend/config/settings.py
  backend/requirements.txt
  docker-compose.yml
  nginx/nginx.conf
Labels: Chore

#79 Fix: swagger 접근 완료
  nginx/nginx.conf
Labels: Fix

#88 Feat : cadvisor, prometheus, grafana 연동완료
  .gitignore
  .idea/misc.xml
  backend/requirements.txt
  docker-compose.yml
  monitoring/grafana/.gitignore
  monitoring/grafana/Dockerfile
  monitoring/grafana/grafana.ini
  monitoring/grafana/provisioning/dashboards/Docker Prometheus Monitoring.json
  monitoring/grafana/provisioning/dashboards/dashboard.yml
  monitoring/grafana/provisioning/datasources/datasource.yml
  monitoring/prometheus/prometheus.yml
Labels: Feat

#95 Fix: 대답과 질문 관계수정
  backend/apps/chat_consumer.py
Labels: Fix

#97 feat : dall-e 비동기처리완료 & s3저장완료
  backend/diary/tasks.py
  backend/diary/views.py
  backend/storage.py
Labels: Feat

#109 feat : id 별 조회제한 (ft. 마지막 PR!!!)
  backend/apps/views.py
  backend/diary/views.py
Labels: Chore, Comment, Feat
